### ISSUE TITLE
Error deploy with one click on vercel

### ISSUE THREAD

**Issue by fernandogprieto** [kuizuo/blog#281]
```
[ERROR] Error: Unable to build website for locale zh-CN.

at tryToBuildLocale (/vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/commands/build.js:53:19)

at async /vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/commands/build.js:64:9

at async mapAsyncSequential (/vercel/path0/node_modules/.pnpm/@docusaurus+utils@3.2.0_@docusaurus+types@3.2.0/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)

at async Command.build (/vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
[cause]: Error: Invalid name=docusaurus-plugin-vercel-analytics version number=3.3.2.
All official @docusaurus/* packages should have the exact same version as @docusaurus/core (number=3.2.0).
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?

at /vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/server/siteMetadata.js:66:19
at Array.forEach (<anonymous>)
at checkDocusaurusPackagesVersion (/vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/server/siteMetadata.js:61:49)
at createSiteMetadata (/vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/server/siteMetadata.js:80:5)

at createSiteProps (/vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/server/site.js:74:64)

at loadSite (/vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/server/site.js:128:25)

at async buildLocale (/vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/commands/build.js:105:18)

at async tryToBuildLocale (/vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/commands/build.js:46:13)

at async /vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/commands/build.js:64:9

at async mapAsyncSequential (/vercel/path0/node_modules/.pnpm/@docusaurus+utils@3.2.0_@docusaurus+types@3.2.0/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)

at async Command.build (/vercel/path0/node_modules/.pnpm/@docusaurus+core@3.2.0_@docusaurus+types@3.2.0_eslint@8.57.0_react-dom@18.3.1_react@18.3.1_typescript@5.3.3/node_modules/@docusaurus/core/lib/commands/build.js:62:5)
}
[INFO] Docusaurus version: 3.2.0
Node version: v20.12.2
ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1

```

**Comment by fernandogprieto** [comment]
It's for an error on vercel pnpm 9.1.1

https://github.com/Cambly/syntax/pull/424

**Comment by kuizuo** [comment]
Vercel only supports up to pnpm version 9.0.4. However, my project is set to version 9.1.1. I will create a PR later to downgrade the pnpm version to fix this issue.

Thank you for your contribution. ❤️
